[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200