[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"   # use "build" if Create React App

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200